# Generated by Django 4.1 on 2022-08-31 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='roles',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Solution Provider', 'Solution Provider'), ('Solution Seeker', 'Solution Seeker')], max_length=255, null=True),
        ),
    ]
